### ISSUE TITLE
Client can connect and disconnect to the chat server

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#1]
US - 1
2 hrs

**Comment by JacobAKnox** [comment]
I don't think the tests actually test the server code, you should make a mock client, or two and connect it to the server socket
You can then send a message to the "chat message" channel and check that you get it back.

You might want to add an event for disconnects, even if it doesn't do much for now

**Comment by JEmersonLawrance** [comment]
both implemented, going to move this to done

**Comment by JacobAKnox** [comment]
task complete
