### ISSUE TITLE
JoinPanel and DisplayNameForm components not rendering correctly on homepage

### ISSUE THREAD

**Issue by JEmersonLawrance** [TheFiveMemberTeam/Retrograde-DarkOrbit#22]
(Viewed on Firefox)

When the web browser is shrunk horizontally, the components visually collide with each other.

Before they were aligned vertically, with one placed atop the other, this is probably what we want them to look like.

**Comment by JacobAKnox** [comment]
fixed in
https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/commit/efcfc03d1dca3dcc2348d4bf76a73e71460fda06
