### ISSUE TITLE
Button to create a lobby (and get join code)

### ISSUE THREAD

**Issue by RayyanOIT** [TheFiveMemberTeam/Retrograde-DarkOrbit#3]
US - 2
2 hr

**Comment by JacobAKnox** [comment]
https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/blob/00e5d68b48cbd4564394e9e1c71d03cdaef065d1/server/lobbies/generate_random_lobby_key.js#L1-L12
This whole file is redundant, should be deleted.

https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/blob/00e5d68b48cbd4564394e9e1c71d03cdaef065d1/server/lobbies/lobbies.js#L25-L34
There is probably a better way to do this, but this works for now.

https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/blob/00e5d68b48cbd4564394e9e1c71d03cdaef065d1/server/lobbies/lobbies.js#L38-L39
you should make sure the lobby doesn't already exist. 

https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/blob/00e5d68b48cbd4564394e9e1c71d03cdaef065d1/server/lobbies/lobbies.js#L37
You aren't using the `lobby_list`

https://github.com/TheFiveMemberTeam/Retrograde-DarkOrbit/blob/00e5d68b48cbd4564394e9e1c71d03cdaef065d1/server/lobbies/lobbies.test.js#L51
Doesn't actually test creating a lobby

**Comment by JacobAKnox** [comment]
Chat messages do not send for created lobbies.
User_id is not passed to join_lobby, so usernames are not given assigned properly
In consistent semi-colons.
Code is not displayed in the lobby.
