### ISSUE TITLE
Sending and receiving point allocation updates from client and server  - US5

### ISSUE THREAD

**Issue by JosephTenEyck** [TheFiveMemberTeam/Retrograde-DarkOrbit#34]
1.5 hr
Every second the client sends a bag of what all the point allocations are
Server verifies (don't allocate more than you have, none are less than 0)
Sends OK or error
On error send the last valid update, client should change UI and client state to reflect this.

**Comment by JacobAKnox** [comment]
reviewed during the meeting and fixed the last issue.
moving to done
