### ISSUE TITLE
Timer is not kept across page refresh

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#39]
3 hr
If the page is refreshed, the timer is blank until the next phase update

**Comment by JosephTenEyck** [comment]
Have server send the absolute time it sent the START TIMER event to the client along with the event itself. That way, whenever the client gets the information, it is counting down to an expected and server known time.

**Comment by JacobAKnox** [comment]
bug was fixed and task is ready for review, see PR #68
