### ISSUE TITLE
Button to join a lobby

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#5]
US - 2
1 hr

**Comment by JacobAKnox** [comment]
I'm aware that the navigation call isn't tested, but jest would not record it being called so I could test it.

**Comment by Freddyh11** [comment]
Review complete. good job Jacob, went over and saw you completed all testing and completed all logic for the testing.

**Comment by JacobAKnox** [comment]
Task complete
