### ISSUE TITLE
Display game over phase UI  - US7

### ISSUE THREAD

**Issue by JEmersonLawrance** [TheFiveMemberTeam/Retrograde-DarkOrbit#51]
1 hr
- functional chat box
- who won the game
- exit to lobby button
- redirect to lobby after phase ends

redirect to the game over page
game over page
	chat
	winners
	stay for 15 sec 
once the client receives win data, handle updating the UI

**Comment by JacobAKnox** [comment]
Todo:
- [ ] redirect to the game over page after 15 seconds
- [ ] game over page
- [ ] chat
- [ ] winners
- [ ] once the client receives win data, handle updating the UI

**Comment by JacobAKnox** [comment]
There isn't anything on the back end for sending the winner info, but the front end is hooked up, ready for review
