### ISSUE TITLE
Clean up unnesceary console.logs

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#70]
30 min

**Comment by JosephTenEyck** [comment]
Make a new branch for this.

**Comment by JacobAKnox** [comment]
Quick notes:
this should have been on an new branch not directly to main

more prints that should be removed or a meaningful message added, perhaps changed to console.error or console.warn
index.js lines: 63, 67, 83, 125, 260, 273
game.js: 86, 87, 98
lobbies.test.js: 42, 53
sessions.js: 19

**Comment by Freddyh11** [comment]
@JacobAKnox would you like me to revert the changes and create a new branch for this? or should I just continue with the changes on main?

**Comment by JacobAKnox** [comment]
@Freddyh11  keep the changes on main, but make a new branch for future changes

**Comment by JacobAKnox** [comment]
Looks good, already merged into main

**Comment by JosephTenEyck** [comment]
Done
