### ISSUE TITLE
US12 Ability function for increase/decrease status bar ability

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#83]
30 min

**Comment by JacobAKnox** [comment]
All the logic for the ability handler was already correct.
What should have been done is write a function that conforms to the ability function definition: `function ability(lobbycode, playerid, data)`
Then add that to the ability function map in `get_ability_function` with an appropriate key. 
Keys can be found under the `ability` key in role_data.json

**Comment by Freddyh11** [comment]
@JacobAKnox, So should I revert back to the original code you had before? or is the implementation I had okay to keep and also add the changes you requested?

**Comment by JacobAKnox** [comment]
@Freddyh11 revert just the change in `use_ability` your implementation is redundant
