### ISSUE TITLE
Move status bars to a permanent  UI location

### ISSUE THREAD

**Issue by JacobAKnox** [TheFiveMemberTeam/Retrograde-DarkOrbit#87]
30 min
they are currently at the top of the screen, they should be somewhere in the game panel

**Comment by JosephTenEyck** [comment]
Make a new branch for this.

**Comment by Freddyh11** [comment]
Ill start working on this Tuesday or Wednesday... I might get started today for a couple of minutes

**Comment by JacobAKnox** [comment]
the role panel and time should also probably be on the side, neither needs to be that wide.
You might want to update from main, the role panel is a bit taller now

**Comment by JacobAKnox** [comment]
I like the new changes, go ahead and merge to main then move to done

**Comment by JosephTenEyck** [comment]
Done
