### ISSUE TITLE
US15 - Add status bar changes to the queue each turn

### ISSUE THREAD

**Issue by JosephTenEyck** [TheFiveMemberTeam/Retrograde-DarkOrbit#92]
1 hr
Take a "snapshot" of the statusbars at the start of each turn
compare to the end of the turn, add a message to the queue for each bar saying % it changed

**Comment by JacobAKnox** [comment]
Joseph and I reviewed this few notes:
Rename the startTurn and endTurn should be renamed to better represent what they do, maybe something like take status bar snapshot, queue status bar changes.
on line 313 there is an easier way to copy an object, i believe its called structured clone
These functions should be called somewhere probably in gameLoop
